name: Run tests on pushing new commits
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Check with Gradle
        run: ./gradlew clean check

      - name: Commit check
        uses: docker://commitsar/commitsar:latest@sha256:4e1d112924e8cffc829c39291f26e11d45539b40204f287647cac34bbfc4654c
